### ISSUE TITLE
修改go编译器允许代码存在未使用的变量和包

### ISSUE THREAD

**Issue by fastfading** [wangkechun/golang-learn#1]
经验证无效

改后编译的comile  与原来一样
不清楚哪里出了 问题

go 1.7  macos

**Comment by wangkechun** [comment]
go install -a -x cmd/compile ?

**Comment by wangkechun** [comment]
https://gist.github.com/wangkechun/c2e3cb24df27909faebd9580477af6ad
go1.7.1使用这个

**Comment by fastfading** [comment]
问题已解决
问题根源在于  编译 compile的时候需要加上 -a 选项
这样才是从头编译，  不然修改代码不起作用，
请更新教程。以便后人。

另外  这段代码在做什么？  这段我没有修改
- cmd.Stdout = &buf
- cmd.Stderr = &buf
- cmd.Stdout = os.Stdout
- cmd.Stderr = os.Stderr

2016-11-22 11:17 GMT+08:00 wangkechun notifications@github.com:

**Comment by wangkechun** [comment]
写文章的时候用的go版本是go1.5，那个时候是不需要加上-a参数的

**Comment by wangkechun** [comment]
后面一段是让go get输出进度
